name: Pylint

# Trigger when branches are pushed
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      # Set Python version
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Cache dependencies
      - name: Cache dependencies setup
        uses: actions/cache@v3
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements-ci.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      # Pylint
      - name: Pylint
        run: pylint src --ignore=tests