name: Report
on: [push]
jobs:
  run:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: iterative/setup-cml@v1
      - uses: iterative/setup-dvc@v1

      # dvc pull files
      - name: local config info GDrive
        run: |
          pip install -r requirements.txt
          dvc remote modify --local myremote gdrive_service_account_json_file_path remla15-57766ff41451.json
          dvc pull

      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dvc repro

          cat outputs/metrics.yaml >> report.md
          cml comment create report.md